/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fl.zaplify.gui;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import fl.zaplify.util.AppIcon;

/**
 *
 * @author MSI CYBORG
 */
public class SelectUserRole extends javax.swing.JFrame {

    /**
     * Creates new form SelectUserRole
     */
    public SelectUserRole() {
        initComponents();
        UpdateComponents();
    }

    public void UpdateComponents() {
        AppIcon.applyIcon(this);

        jPanel2.putClientProperty(FlatClientProperties.STYLE, "arc:999");
        adminBtn.putClientProperty(FlatClientProperties.STYLE, "arc:50");
        stockManager.putClientProperty(FlatClientProperties.STYLE, "arc:50");
        casierBtn.putClientProperty(FlatClientProperties.STYLE, "arc:50");
        backBtn.putClientProperty(FlatClientProperties.STYLE, "arc:999");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        casierBtn = new javax.swing.JButton();
        adminBtn = new javax.swing.JButton();
        stockManager = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Jura", 1, 36)); // NOI18N
        jLabel1.setText("Select user Type");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 330, 50));

        jPanel2.setBackground(new java.awt.Color(104, 186, 127));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 10));

        jLabel2.setFont(new java.awt.Font("Carmen Sans SemiBold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(114, 112, 112));
        jLabel2.setText("Cashier");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 80, 30));

        jLabel3.setFont(new java.awt.Font("Carmen Sans SemiBold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(114, 112, 112));
        jLabel3.setText("System Admin");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 150, 30));

        jLabel4.setFont(new java.awt.Font("Carmen Sans SemiBold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(114, 112, 112));
        jLabel4.setText("Inventory Manager");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, 30));

        casierBtn.setBackground(new java.awt.Color(255, 255, 255));
        casierBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fl/zaplify/img/icons8-cashier-100.png"))); // NOI18N
        casierBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casierBtnMouseClicked(evt);
            }
        });
        casierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casierBtnActionPerformed(evt);
            }
        });
        jPanel1.add(casierBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 250, 240));

        adminBtn.setBackground(new java.awt.Color(255, 255, 255));
        adminBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fl/zaplify/img/icons8-administrator-male-100.png"))); // NOI18N
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });
        jPanel1.add(adminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 250, 240));

        stockManager.setBackground(new java.awt.Color(255, 255, 255));
        stockManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fl/zaplify/img/icons8-inventory-100.png"))); // NOI18N
        jPanel1.add(stockManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 250, 240));

        backBtn.setBackground(new java.awt.Color(244, 244, 244));
        backBtn.setForeground(new java.awt.Color(114, 112, 112));
        backBtn.setText("Back");
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 130, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fl/zaplify/img/icons8-close-30.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminBtnActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void casierBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casierBtnMouseClicked
        // TODO add your handling code here:
        loginMember loginM = new loginMember();
        loginM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_casierBtnMouseClicked

    private void casierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casierBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casierBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton casierBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton stockManager;
    // End of variables declaration//GEN-END:variables
}
